# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = false
loom.platform = neoforge

# Mod Properties
mod_version = 0.1.0

maven_group = org.thinkingstudio
archives_base_name = ForgematicaPrinter

# Dependencies (mafglib / forgematica)
mafglib_version = 0.1.11-mc1.20.4
forgematica_version = 0.1.7-mc1.20.4

# Minecraft, NeoForge and mappings versions
minecraft_version = 1.20.4
mappings_version = 1.20.4+build.3

neoforge_version = 20.4.239

curseforge_id=1223456
modrinth_id=oqw1j8E7
