# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = false
loom.platform = forge

# Mod Properties
mod_version = 0.1.0

maven_group = org.thinkingstudio
archives_base_name = ForgematicaPrinter

# Dependencies (mafglib / forgematica)
mafglib_version = 0.1.13-mc1.20.1
forgematica_version = 0.1.12-mc1.20.1

# Minecraft, NeoForge and mappings versions
minecraft_version = 1.20.1
mappings_version = 1.20.1+build.10

forge_version = 1.20.1-47.3.5

curseforge_id=1223456
modrinth_id=oqw1j8E7
