# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = false
loom.platform = neoforge

# Mod Properties
mod_version = 0.1.0

maven_group = org.thinkingstudio
archives_base_name = ForgematicaPrinter

# Dependencies (mafglib / forgematica)
mafglib_version = 0.1.15-mc1.20.6
forgematica_version = 0.1.8-mc1.20.6

# Minecraft, NeoForge and mappings versions
minecraft_version = 1.20.6
mappings_version = 1.20.6+build.3
yarn_patch=1.20.6+build.4

neoforge_version = 20.6.125

curseforge_id=1223456
modrinth_id=oqw1j8E7
